version: '3'
services:
  api:
    container_name: santex-backend-challenge
    volumes:
      - .:/app
    restart: always
    build: .
    environment: 
      - .env
    ports:
      - '4000:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'